#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS:[11pt,oneside]
#+LATEX_HEADER: \usepackage{article}


#+TITLE: jquery学习笔记
#+AUTHOR: 万泽(德山书生)
#+CREATOR: wanze(<a href="mailto:a358003542@gmail.com">a358003542@gmail.com</a>)
#+DESCRIPTION: 制作者邮箱：a358003542@gmail.com

* jquery选择语法
jquery的选择语法和beautifulsoup的那种选择语法很是类似，这里不赘述了。唯一值得提醒的就是jquery这样:
#+BEGIN_EXAMPLE
$(selector)
#+END_EXAMPLE
选择之后返回是一个数组类型。后面也许某些有特色的选择风格会加在下面。


* 文档初始化之后执行的动作
#+BEGIN_SRC js
$(document).ready(function(){

   // jQuery methods go here...

});
#+END_SRC


* 获取屏幕的宽度和高度
#+BEGIN_SRC js
var width = $(window).width()
var height = $(window).height()
#+END_SRC

* hide方法
实际上就是css设置 ~display:none~ 。
#+BEGIN_SRC js
$('#test').hide()
#+END_SRC

这样将隐藏所有id为test的元素。


* 给某个元素添加点击事件并绑定某个函数动作
#+BEGIN_EXAMPLE
$(selector).click(function)
#+END_EXAMPLE

类似的事件还有:
- dbclick :: 双击事件
- focus :: 焦点事件
- mousemove :: 鼠标悬停事件


** 鼠标事件
- click :: 鼠标单击时触发；
- dblclick :: 鼠标双击时触发；
- mouseenter :: 鼠标进入时触发；
- mouseleave :: 鼠标移出时触发；
- mousemove :: 鼠标在DOM内部移动时触发 （接受e ，e.pageX是鼠标x值，e.pageY是鼠标Y值）
- hover :: 鼠标进入和退出时触发两个函数，相当于mouseenter加上mouseleave。

** 键盘事件
键盘事件仅作用在当前焦点的DOM上，通常是<input>和<textarea>。

- keydown :: 键盘按下时触发；
- keyup :: 键盘松开时触发；
- keypress :: 按一次键后触发。


** 其他事件
focus：当DOM获得焦点时触发；
blur：当DOM失去焦点时触发；
change：当<input>、<select>或<textarea>的内容改变时触发；
submit：当<form>提交时触发；
ready：当页面被载入并且DOM树完成初始化后触发。


** 取消某个事件绑定
#+BEGIN_EXAMPLE
a.off('click', hello);
#+END_EXAMPLE


* jquery的DOM操作

** text方法
返回所选元素的文本信息。如果选中了多个元素，所有的元素的字符串将合并。

设置字符串具体就是在 ~text()~ 方法里面，所有选中的元素的innerText都将更改。

** html方法
类似上面的text方法，包括HTML标记。

** val方法
是针对form 表单元素提取其value属性值或设置value值的。

** attr方法
获取某个元素的某个属性值。

设置值如下所示:
#+BEGIN_EXAMPLE
$("button").click(function(){
  $("#w3s").attr("href","http://www.w3school.com.cn/jquery");
});
#+END_EXAMPLE

** removeAttr方法 
删除属性
#+BEGIN_EXAMPLE
// <div id="test-div" name="Test" start="1">...</div>
var div = $('#test-div');
div.hasAttr('name'); // true
div.attr('name'); // 'Test'
div.attr('name', 'Hello'); // div的name属性变为'Hello'
div.removeAttr('name'); // 删除name属性
div.attr('name'); // undefined
#+END_EXAMPLE




- css() :: 修改css属性
#+BEGIN_EXAMPLE
$('#test-css li.dy>span').css('background-color', '#ffd351').css('color', 'red');
#+END_EXAMPLE

#+BEGIN_EXAMPLE
var div = $('#test-div');
div.hasClass('highlight'); // false， class是否包含highlight
div.addClass('highlight'); // 添加highlight这个class
div.removeClass('highlight'); // 删除highlight这个class
#+END_EXAMPLE



-----

- append() :: 添加一个子节点
- prepend() :: 添加一个子节点，到最前。
- before() :: 某个节点之前插入
- after() :: 某个节点之后插入
- remove() :: 删除某个节点




* ajax





